import random
s = "01234567890"
passlen = 4
p =  "".join(random.sample(s,passlen ))
print("Welcome to the Cows and Bulls Game!")
print("The random number generated by system is: ",p)
while True:
    b = 0
    c = 0
    i = int(input("Enter a number: "))
    l1=[int(x) for x in str(i)]
    l2=[int(y) for y in str(p)]
    print(l1)
    print(l2)
    if i >= 1000 and i <= 9999:
        for j in range(4):
            if l1[j] == l2[j]:
                j+=1
                c+=1
            else:
                continue
        for k in l1:
            if k in l2:
                b+=1
            else:
                continue

    else:
        print("Entered number is not a four digit number!")

    print("Number of cows:",c,"& Number of Bull:",b-c)
    if c==4:
        print("Entered number is guessed right!")
        exit()
